/**
 * PayMaya API constants
 */
const ENVIRONMENTS = {
  SANDBOX: 'SANDBOX',
  PRODUCTION: 'PRODUCTION'
};

const API_ENDPOINTS = {
  [ENVIRONMENTS.SANDBOX]: 'https://pg-sandbox.paymaya.com',
  [ENVIRONMENTS.PRODUCTION]: 'https://pg.maya.ph'
};

const PAYMENT_URLS = {
  [ENVIRONMENTS.SANDBOX]: 'https://payments-web-sandbox.paymaya.com',
  [ENVIRONMENTS.PRODUCTION]: 'https://payments.maya.ph'
};

const WEBHOOK_DOMAINS = {
  [ENVIRONMENTS.SANDBOX]: ['13.229.160.234', '3.1.199.75'],
  [ENVIRONMENTS.PRODUCTION]: ['18.138.50.235', '3.1.207.200']
};

const WEBHOOK_EVENTS = {
  CHECKOUT_SUCCESS: 'CHECKOUT_SUCCESS',
  CHECKOUT_FAILURE: 'CHECKOUT_FAILURE',
  CHECKOUT_DROPOUT: 'CHECKOUT_DROPOUT',
  PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_EXPIRED: 'PAYMENT_EXPIRED',
  PAYMENT_CANCELLED: 'PAYMENT_CANCELLED'
};

module.exports = {
  ENVIRONMENTS,
  API_ENDPOINTS,
  PAYMENT_URLS,
  WEBHOOK_DOMAINS,
  WEBHOOK_EVENTS
};
